### PR TITLE
Use Powershell 6 GA and PowerCLI 10 GA

### PR DESCRIPTION
**Pull request by kars7e**
* Use official powershell 6.x GA image based on Ubuntu 16.04
* Install PowerCLI and PowerNSX from PSGallery

### CODE REVIEW

**Comment by jakerobinson** [comment]
You're changing from Photon to Ubuntu here. I don't mind having a different ubuntu branch, but we're going to keep this photon. stay tuned :)

**Comment by kars7e** [comment]
Indeed, I actually ended up using photon as well, as it's smaller. Here is my version (it doesn't have the powercli installed, but just one more `Save-Module` line) https://github.com/kars7e/dispatch/blob/8a8f494f715c6ef38fb0b16f677b0720d67f5c1f/images/base-images/powershell/Dockerfile

**Comment by jakerobinson** [comment]
@kars7e Can you submit a new PR to an ubuntu16_04 branch? Your commit is great, and I'd love to put it up, just not on the master branch, which is photon

**Comment by kars7e** [comment]
Will do!

**Pull request closed without merging**
