### PR TITLE
Updated PowervRA version

### PR DESCRIPTION
**Pull request by jjasghar**
https://github.com/jakkulabs/PowervRA/releases/tag/v2.1.0 was released :)

### CODE REVIEW

**Comment by alanrenouf** [comment]
Thanks @jjasghar, please can you sign the CLA

**Comment by jjasghar** [comment]
@alanrenouf Done 🤘

**Comment by alanrenouf** [comment]
Thanks, and thanks for the update!

**Comment by alanrenouf** [comment]
I undid these changes as there is an issue with the zip file

**Comment by jjasghar** [comment]
:( awww....

**Pull request merged**
